universe   = vanilla
getenv     = True
executable = forestCloning.sh
+JobFlavour  = "workday"
requirements = ((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
RequestCpus = 1

log        = condor/log/pthat15_emb_Pbgoing_forestCloning_forestCloning.log
output     = condor/log/pthat15_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat15_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat15_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat30_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat30_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat30_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat30_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat50_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat50_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat50_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat50_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat80_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat80_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat80_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat80_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat120_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat120_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat120_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat120_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat170_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat170_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat170_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat170_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat220_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat220_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat220_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat220_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat280_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat280_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat280_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat280_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat370_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat370_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat370_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat370_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat460_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat460_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat460_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat460_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue

log        = condor/log/pthat540_emb_Pbgoing_forestCloning.log
output     = condor/log/pthat540_emb_Pbgoing_forestCloning.out
error      = condor/log/pthat540_emb_Pbgoing_forestCloning.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat540_Pbgoing_embedded.root /eos/user/g/gnigmatk/ana/pPb8160/embedding/Pbgoing/forest
queue
