universe   = vanilla
getenv     = True
executable = forestClonning.sh
+JobFlavour  = "workday"
requirements = ((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
RequestCpus = 2

log        = condor/log/pthat15_pythia_pgoing.log
output     = condor/log/pthat15_pythia_pgoing.out
error      = condor/log/pthat15_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat15_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat30_pythia_pgoing.log
output     = condor/log/pthat30_pythia_pgoing.out
error      = condor/log/pthat30_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat30_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat50_pythia_pgoing.log
output     = condor/log/pthat50_pythia_pgoing.out
error      = condor/log/pthat50_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat50_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat80_pythia_pgoing.log
output     = condor/log/pthat80_pythia_pgoing.out
error      = condor/log/pthat80_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat80_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat120_pythia_pgoing.log
output     = condor/log/pthat120_pythia_pgoing.out
error      = condor/log/pthat120_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat120_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat170_pythia_pgoing.log
output     = condor/log/pthat170_pythia_pgoing.out
error      = condor/log/pthat170_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat170_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat220_pythia_pgoing.log
output     = condor/log/pthat220_pythia_pgoing.out
error      = condor/log/pthat220_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat220_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat280_pythia_pgoing.log
output     = condor/log/pthat280_pythia_pgoing.out
error      = condor/log/pthat280_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat280_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat370_pythia_pgoing.log
output     = condor/log/pthat370_pythia_pgoing.out
error      = condor/log/pthat370_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat370_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat460_pythia_pgoing.log
output     = condor/log/pthat460_pythia_pgoing.out
error      = condor/log/pthat460_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat460_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue

log        = condor/log/pthat540_pythia_pgoing.log
output     = condor/log/pthat540_pythia_pgoing.out
error      = condor/log/pthat540_pythia_pgoing.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/unembedded/pgoing/HiForestSkim_pPb_MC_pthat540_pgoing_unembedded.root /eos/user/g/gnigmatk/ana/pPb8160/pythia/pgoing/forest
queue
