universe   = vanilla
getenv     = True
executable = run_dijetAna.sh
+JobFlavour  = "workday"
requirements = ((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
RequestCpus = 4

log        = condor/log/pthat15_emb_Pbgoing_nocut.log
output     = condor/log/pthat15_emb_Pbgoing_nocut.out
error      = condor/log/pthat15_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat15_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_15.root 1 1 15 30
queue

log        = condor/log/pthat30_emb_Pbgoing_nocut.log
output     = condor/log/pthat30_emb_Pbgoing_nocut.out
error      = condor/log/pthat30_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat30_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_30.root 1 1 30 50
queue

log        = condor/log/pthat50_emb_Pbgoing_nocut.log
output     = condor/log/pthat50_emb_Pbgoing_nocut.out
error      = condor/log/pthat50_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat50_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_50.root 1 1 50 80
queue

log        = condor/log/pthat80_emb_Pbgoing_nocut.log
output     = condor/log/pthat80_emb_Pbgoing_nocut.out
error      = condor/log/pthat80_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat80_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_80.root 1 1 80 120
queue

log        = condor/log/pthat120_emb_Pbgoing_nocut.log
output     = condor/log/pthat120_emb_Pbgoing_nocut.out
error      = condor/log/pthat120_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat120_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_120.root 1 1 120 170
queue

log        = condor/log/pthat170_emb_Pbgoing_nocut.log
output     = condor/log/pthat170_emb_Pbgoing_nocut.out
error      = condor/log/pthat170_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat170_Pbgoing_embedded.root 1 1 170 220
queue

log        = condor/log/pthat220_emb_Pbgoing_nocut.log
output     = condor/log/pthat220_emb_Pbgoing_nocut.out
error      = condor/log/pthat220_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat220_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_220.root 1 1 220 280
queue

log        = condor/log/pthat280_emb_Pbgoing_nocut.log
output     = condor/log/pthat280_emb_Pbgoing_nocut.out
error      = condor/log/pthat280_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat280_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_280.root 1 1 280 370
queue

log        = condor/log/pthat370_emb_Pbgoing_nocut.log
output     = condor/log/pthat370_emb_Pbgoing_nocut.out
error      = condor/log/pthat370_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat370_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_370.root 1 1 370 460
queue

log        = condor/log/pthat460_emb_Pbgoing_nocut.log
output     = condor/log/pthat460_emb_Pbgoing_nocut.out
error      = condor/log/pthat460_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat460_Pbgoing_embedded.root oEmbedding_pPb8160_Pbgoing_460.root 1 1 460 540
queue

log        = condor/log/pthat540_emb_Pbgoing_nocut.log
output     = condor/log/pthat540_emb_Pbgoing_nocut.out
error      = condor/log/pthat540_emb_Pbgoing_nocut.err
arguments  = /eos/cms/store/group/phys_heavyions_ops/ddesouza/Jets_pPb/MC_withjetid/embedded/Pbgoing/HiForestSkim_pPb_MC_pthat540_Pbgoing_embedded.root 1 1 540 8160
queue
