"""Configuration for hist_analysis."""

from .files import BASE_DIR, DATA_DIRS, MC_DIRS
from .histograms import (
    COMMON_ETA_CM_RANGE,
    DIJET_DELTA_PHI_SELECTION_LABEL,
    DIJET_PTAVE_BINS,
    SINGLE_JET_PT_BINS,
    STANDARD_DIJET_ETA_CUT_INDEX,
    TEST_DIJET_PTAVE_BINS,
    TEST_SINGLE_JET_PT_BINS,
)

__all__ = [
    "BASE_DIR",
    "DATA_DIRS",
    "MC_DIRS",
    "COMMON_ETA_CM_RANGE",
    "DIJET_DELTA_PHI_SELECTION_LABEL",
    "DIJET_PTAVE_BINS",
    "SINGLE_JET_PT_BINS",
    "STANDARD_DIJET_ETA_CUT_INDEX",
    "TEST_DIJET_PTAVE_BINS",
    "TEST_SINGLE_JET_PT_BINS",
]
